services:
  # Run small models locally for development
  vllm-qwen3:
    build:
      context: ../vllm  # Assume vllm repo is cloned next to this one
      dockerfile: docker/Dockerfile.cpu
      network: host
    profiles:
      - local
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - VLLM_CPU_KVCACHE_SPACE=8
      - VLLM_CPU_OMP_THREADS_BIND=0-7  # Adjust cores based on your CPU
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    privileged: true
    shm_size: 4gb
    ipc: host
    command: >
      Qwen/Qwen3-0.6B
      --served-model-name Qwen/Qwen3-0.6B
      --dtype bfloat16
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --tensor-parallel-size 1
      --max-model-len 32768
  # vllm-llama3:
  #   image: vllm/vllm-openai:latest
  #   profiles:
  #     - local
  #   runtime: nvidia
  #   environment:
  #     - HF_TOKEN=${HF_TOKEN}
  #     - NVIDIA_VISIBLE_DEVICES=allx
  #   volumes:
  #     - ~/.cache/huggingface:/root/.cache/huggingface
  #   ports:
  #     - "8001:8001"
  #   ipc: host
  #   command: >
  #     --model meta-llama/Llama-3.1-8B-Instruct
  #     --served-model-name Llama-3.1-8B-Instruct
  #     --gpu-memory-utilization 0.4
  #     --tensor-parallel-size 1
  #     --max-model-len 32768
  #   networks:
  #     - common_net

  vllm-coder:
    image: vllm/vllm-openai:latest
    profiles:
      - remote
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: >
      --model stelterlab/Qwen3-Coder-30B-A3B-Instruct-AWQ
      --served-model-name qwen3-coder-30B-A3B-Instruct-AWQ
      --gpu-memory-utilization 0.4
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --tensor-parallel-size 1
      --max-model-len 65536
    networks:
      - common_net
  vllm-gpt-oss:
    image: vllm/vllm-openai:latest
    profiles:
      - remote
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8001:8001"
    ipc: host
    command: >
      --model openai/gpt-oss-20b
      --served-model-name gpt-oss-20b
      --gpu-memory-utilization 0.4
      --tensor-parallel-size 1
      --max-model-len 32768
    networks:
      - common_net
networks:
  common_net:
    external: true
    name: common_network
