services:
  vllm-coder:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: >
      --model stelterlab/Qwen3-Coder-30B-A3B-Instruct-AWQ
      --served-model-name qwen3-coder-30B-A3B-Instruct-AWQ
      --gpu-memory-utilization 0.4
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --tensor-parallel-size 1
      --max-model-len 65536
    networks:
      - common_net
  vllm-gpt-oss:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8001:8001"
    ipc: host
    command: >
      --model openai/gpt-oss-20b
      --served-model-name gpt-oss-20b
      --gpu-memory-utilization 0.4
      --tensor-parallel-size 1
      --max-model-len 32768
    networks:
      - common_net
networks:
  common_net:
    external: true
    name: common_network