version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:nightly
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: >
      mistralai/Devstral-Small-2-24B-Instruct-2512
      --served-model-name devstral
      --api-key token-abc123
      --gpu-memory-utilization 0.9
      --tool-call-parser mistral
      --enable-auto-tool-choice
      --tensor-parallel-size 1
      --max-model-len 30720


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"   # the default port used by Prometheus
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml # mount Prometheus config file

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000" # the default port used by Grafana