global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - 'vllm-coder:8000'
          - 'vllm-gpt-oss:8001'
  - job_name: litellm
    static_configs:
      - targets:
          - 'litellm:4000'
